# Generated by Django 4.1.1 on 2022-12-05 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='brand_name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='quantitie',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_img',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
