# Generated by Django 4.1.1 on 2022-12-05 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce_app', '0002_item_brand_name_item_category_item_quantitie_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='brand_name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.RemoveField(
            model_name='item',
            name='quantitie',
        ),
    ]
