# Generated by Django 4.1.1 on 2022-12-05 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce_app', '0004_item_brand_name_item_category_item_quantitie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='quantitie',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
